export default {
    AGORA_CLIENT_INITIALIZED:   'agora/CLIENT_INITIALIZED',
    AGORA_SET_CURRENT_STREAM:   'agora/SET_CURRENT_STREAM',
    AGORA_SET_CLIENT_ROLE:      'agora/SET_CLIENT_ROLE',
    AGORA_EXIT_STREAM:          'agora/EXIT_STREAM',
    AGORA_SET_IS_INSIDE_STREAM: 'agora/AGORA_SET_IS_INSIDE_STREAM',
    AGORA_SET_STREAM_ID:        'agora/AGORA_SET_STREAM_ID',
    AGORA_SET_HOST_ID:        'agora/AGORA_SET_HOST_ID',
};
